---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-clog-credentials
  namespace: dev
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgDSG9+DHrLOZ1SW27Gc/xWuf5ozqhMqDj84G+L6kCouGJRKqHa2Q+00OEJivv7KmKvV0OW8E1RpfQU6PstXXAEbTy5UgkMU9IadvD2unPLNLGtRYONeDs9zX+9mJ+7fdlNsEI+biUISA7ROMlBOjdhoQrORf4HstnLTSXNOjj01PLzDO4ydZ0eqSDALYIXWIU4R2nKCAZ4c8ZfmnVy+5ypHzyWqATD+cnDT1Tdk4nev8NVSVyoI+Rvci7cYjR9iUXM1l/7QSddE8MA3umXMJ8Cd3VjkaowZ1nWFh5QX0SOfOMNaTuNoSMda7cWUahvSEXfmUmZxgDeYRmKV8QFrKNdKs1nMysF+jXIrYj1H3T3cr40Y8JeQiheSlsISNhn/pOnSZ5ytbJnsT1t0HzIvmGVJrpMmoLqvojS+fdt79etFa6h2vxnOCBcMPC8A6qspJpmQUz9S5h3lFsgAQlsXi7grydyZbUxyj6wC0JmNP5MRfuTRBrMX+yfLK6VkTffx0LTqmzPJiXxTuoHnwCqp1homKYfljuiu3CYV+NjuzL8HBiuKAaab5jC419QKb7XVXmnERGv2SpwVIVkm4TBu1R9z82mtOzJ6m4ujgr9uRZGhtpzgv/bvInqgsnRX9tqWNQOGnzOdVU2pRE9rfz4PgBC6EkgNY6/E/yAwL3s3WuVUeZiaFXXXZey/mE61xhMplw7RDv442RBQaw==
    MINIO_SECRET_KEY: AgCwHNRkpmJphr4R5wZ7TnRXuC7qpHiwJKeeE+a6cDhPuuWQwjH26Wjpb6TooN67NjER8CgNlaQdidEvO6HtVLNTPw9VDpcj5HCanvF5wCQjyNm3HSJCDJZETMMfJjVJYyJwJZDimu2p5YyONGgb4O3KwJIGCIBGXOPIix1RVQz1kAKNhtFKoNwqqqNXdE5Syl49swWoBXSck+bzoP+OhY+MklY4G1JU6JVkO43jacjuGXnz7Q4kFZlLrfcuIgMASxwuMg3eVWlm2eEMtCL5NbK1hTh7ifvuKBQBfMHZdd0vsOaniMCNFr5wTq6/NQy2mgIjDWrFqh7HWTGCCwJP0OXXZu+lFDJCfKUL5hVT5sp0O3vm19q3BluTTNWnhHdG2uOw9FCIo4J/x/LL/h8V4yowQtBBDI6kaXwgyScEQWt/cENJDoxU5ZFG3E9iwaNx3QMtOlKW6fRat9uO2xS1nTPW0Bc5iFimRWXy5DK2wVGfvUSwMHD1fAOmXPw1JvFzgKLN64cQfZBmAldHni7XdsWZYeJOHO4SawOGxSphFYJUowIeiyb2DWvPzKqTY5mzNf5txHpRGYgXLebB0HXOPF4978E6xPgiDZx0EUxoKru4w5+htornqC3v5c5tns6i2La/WTOmVU2Udfb1IpibM3X2cuMEC+DyHcCyT8qZ1DK5yMJEx8BfvtVCnpFop63L8lFFV5D+OUAg9GGUDyKbuh224U95/L2VIe9NL3ZXmhw04A==
  template:
    metadata:
      name: minio-clog-credentials
      namespace: dev
