---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-clog-credentials
  namespace: prod
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgBEczQHhWNQ5/QyESNNrQJNqShlWK+t7qPt/KGbVk0/aB3zvx1KRPuk1/hs9UOAljo+v+f//aqFiYnru4kbWAYNnbxOLYaBAw2IZ1Mkd2+MqXinlCv8tAetB1ZEgArFT6w9WLSGuuINQg5ZoBlS5rF25NRGbbm2OokL0HvvjadRKOiq5SEUoZf/xgKPZj4i7VraxV3GeZjZzjhml7bF82DG81tmJdxVggq4xAdzYq+yKHGZe9Pb2hRuiedkuWH6hT05MF/AuOnTMMtdi7cf9w0D8A+Dvpb4/OlIAQ7JALjhaCgMuVpFPYwDbzIlO1LFTGTIOj7NC1Dn5zP0jS2wUVAGuHbmuFhplHFR8fmkmkYt593ZotRsSxmUfWeS+JoUZXlPMeb+K4Xjl1ZcdKQY4ZIloTWAdYh0ch3SSHiYfQVRbESh9vMgkaeaPPdLCDoWCN3IT47MvZY5reiRS8fngu2w4aoPuxDQI6w/wX5pZGqQrxmsg8ef7HdAE9c+yet951j+LDDGZLSA0KyLU7kwfM3TqK6BCfQAIc9fvWQ7/CGJwXpaNGH2nRwnYTm6CCLpOyBC0P6lXVt8fxjpV4mhP8m8xuHMGulEEqmhvsq8DwXFeVUebIQCDE6BU+PipUk//O4RAPDx8NRRvxSeKLH2lrl49zV14+DLflzdbrnYj6JYy3EYAlT4jvibpVCwrvyQsup7PTwDZPTMYE4=
    MINIO_SECRET_KEY: AgAw5mR+kN17TWVwsU3Uu88YpE9z7Plmrcq+JjY9gBBQRM3beti9+KS7yMOVgenFY0rOd0fIgWqi4fkZXLTm39Fxu1P5LSHzI+VL7eKjP9TxHYsg6YmRMkU1oEi6TwJOWiCqzkJ5hp/teLodWlEbgEwEYW3FEg5O6rRPv4FV49rDnVijpeQAlzgcr4vEX1Rh9c1ZtgmCN0cprnl8HdE3W4zpqnb5MD4a0HYyv1KO1g463/nhL/RiOl9Xz1PoTO+UbeIvmuyWtD1msl0NDAaqosswKGehgAW1zuo4wXzsF8Rq8RR9vPD8gwNknn9euSKIQL/w1EVRCGzW0PD7dRJ0bPfxEFSWFljFa5akxWX+r910TuteVEQFB6/3ozd8qCNzAua0hCrELALC5YAEFpJM9lRFVDKHe9g5568f5319xMr39x7UXfkdT1/dypeUyJOqs5oiB3hlmE7iL2VH09g8lOh3jTJ7BJq+3d7cOUacMj+xqdkY7Sjqnj/JR3B3G1/CAe/8IckZqiCuAAn360HAajPsd1jwD7mmd66MJBiwPH1kzut9c5z2T2mKMi06PqFMk6Ugd/NbX+diI0kR1y9jgGwiwoZqcQ8AIxTVmvcA3ZeW2MrPzt7x3PnzeIfgVltO0wC4ydUacB+aQwf44f9AhWnDY5gi+jiwbYMTaMngJ+oiNyQ4b2sDo9YKMF0NKapqPNCdB+I0BR56snZiQiN6jJF3F7wQW/lcs/9et2R7v5o=
  template:
    metadata:
      name: minio-clog-credentials
      namespace: prod
