---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: dev
spec:
  encryptedData:
    redis-password: AgDRVKoYCiVE9q7oXA1ScYngJSHKwl+yW7t6L65paKN9QS4GZwU6BLwaFR+mC/r+jxbIhUioD6nyFDhHJBdmti8yBLwqnLN7RJSGdvt2ltnziwBkwJBcKfBzpxuQ+I0iqJxVqCHfEIm9OEcQ+uDHBxEb6Ddglmnd2xIxYDbGqT91J0m3q/M7/ilEOl7nW70fWyrSJl3aiITTEN7AwbzfCtYWOfe+hCpeCClpb3CZCY2UNRDrwbIPcpxkJRuP5jZB3cmTTmfMZWEc243jcE8JcjDhfgurh+pdxK23OKN4lI/SHkvXmdav/t+g7Xs8KsSmomqgj47cnYN+gUNQB1pDoYD18mYYHde2eOWMfZtxNsN9muZoGlMZpKEbQdyrpsgsJPGYYD4s9IABjER99Q1RWjPtKjlZeYh0/ELc+Z7WJNoeT1mUmUedcZloHOPcrq3MMk0pN5lAdQlgR7JtqpRbnFTSo2iT5yd4x2iYMPmBq32Pp5lGkuPmsJPqZAbuZkvyeXvpVVIan/Djti4L6vGuDqCSG14sneXyfBhastX+4ZkXiswsKbgUJIB+FXNFb8AALRQsjymInZnDkDNOtuNRhEhwsyOhkG1A4YUF84ks6w3PGtVYVUn9UI+z5KX8USOhSsVB2WMopL/KXI7LC0+gHjEukrxKrHDKDEZTPmpHXbzFZKCQ4Na90kMEkD/m8ICooOtVBRLJVnojF7gk0j/zCk31snQI5cIwTZq+
  template:
    metadata:
      name: redis-credentials
      namespace: dev
    type: Opaque
