{{- if eq .Release.Name "redis-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: prod
spec:
  encryptedData:
    redis-password: AgDJpvm9IZrfMAuU4tgvK3VDtrYZbzKgTZXgx2lR4N1885wHX1XpkWeoRI8p9E0hrqlJ7SvMLRfUWer64X1MO/8ZY4rMml6Vfz3rPHSQOGhaOYOVaOr86n5WuDxSvywkp43YeR5jErGCiq2MZHWLN8aaFU9QHrQGaiNuCkGRgB3EYRcrfp2cN1x5/nOJad1A6ocdKsXykAP09FKSo521Vv+QjK5kajuZpv8M7aSs4+Goj+UK8xjKjLZLSl+x26DJJXP2KJBClDPPXX+xeaYBOXlMpgOuhg87QFpX0XZ/a4mzUU+EU5TpUqRrFvhE3szPiep76hb1rVM8HfSFCUdS5ei4Eom1HITFWmj3LBqyAMseU3QLWq7eyMTfaGSqRBr/7ysOB3qZvqXza92aNWZnNj4EIUxSAoV9U8a6uJK6OdBPSiq9MrsXAPQG595Ev20HWuMSQKg+iq1C6NswftQrJ9PpLIUkFiMK8hBBNSIaPnHb3LQib62VwjdU4C3j91WJM2HN20G5hBsgkSBh/Qglk58SgDundBbdUyKOuK6bgwIRxiaxWCAbfjDy92JgD54CDQ8v3osAauj/kmHKjWRm9QvTS6f03enApFsXwsr27EYzQWB9Fmug8mVV53k4oPlaMcTlAXHQtBqOhpQn+LAvYK3V3gzYaUiuVT+/AXX92n68oVFpG7BBWPMleengOD+OZrfRs51FOp4iHgQQN43Uy2SXxHrUlQ==
  template:
    metadata:
      name: redis-credentials
      namespace: prod
    type: Opaque
{{- end }}
