---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: dev
spec:
  encryptedData:
    clog-password: AgBL6mByFiwTH+ZB4UEiLKD6eY/gnJYC6eP9na1+UiYvB8eyvnDjRPgbz3ipKppuHKTCFCHKbIqif7PWjBZUxCIDOGKQ5R0BufqmXkWkWGvPHV2qB9waZdyYApfUtS0Tnc909qIBb4/ktpyfDo9t0VSJ/bcij+ZwhSHFomKW6HEG3fdjFgzmse+zV4o+3qfm8To01k6X9ETy+IGHTSs7A1/995T8WnCoI7L5FHRaSJ6R9LSpdTvIK/QRAp3AUjltIpQNrsWG0SNHlS5hWDqAypW4E4ruRJD180yNJc0PDuSSVheY/QL4kHEpiqXWhIXPARj41jsC7/V34xYh3/oBieUi4EPG4efi0CwG6Ga54zBC6fty1P4m7oLNZ+8yrZeT+jeaLeHpkr4fkrxghLT0vzSgXO5YZO+C0Ff3O8TKRW/ZHpWEmp8XIIkqGFJvYniQ6M7K/M2QGDPx3uyiCed/Ed1zFHIzAZI5KWezpOM9xX6BGjKHC+2tnSNtY6WmP39LjmlrPkfN8u0g0QyfuU3anBvUdSAluZL6c/VigAgMTVFK+Z9o1AmXD+tpf0ZPTwhAYBMDmxllGJiO7r2KQzVmHZ6ZmzMTOUaEy2vJPgCqcD2+mnYDhVygC5MSWvLeP0NM2m29qmozo36THEILbjTBO/tqwKSyFeg7LVFwNRlgiXj1h5+04SqF8AmjJ8ogWif9xMjpFyR1YLWSfY1TH3x+puElwpEcdaQJxFqW
    postgres-password: AgDk3ofpCvg6g9abAFvtnX7F850eX3ZppnB6RV5szmPBAf6nMjK+td9it98eYnXqpgcHXsC+VCAq0OQoWYaDwC63ctjZZMnKKkfj2pKUFklYXE3APsqL0lLxrovr4plBnJVZkMdaxl73z9qSB9STzmQeRUjm1RQIVkBFKr+Myj5KyWF/WkxfY20oTw8KL1wkai19svp5wZu4VbIvklXeOO0E3nEqf90yljqmTX8UTjEa58hiJSF0CTWdQg8wjwmk84sk/sh3JeaqxcXpmMJu3/QqUcU+KKtxLe4e6fKkIRewFfevnsdSYq5HQ2+F30ycatLQWJrCQPZlNrQbdvqGM3ZkjwWhAOL4aYls6LwFhUvo4747bkCRXRXFNcfcyuVVBvFGsx5DrJpvnDoNJHHSmBMl3pUwYSHhooQYSm2vVEYIA3jS0oF3eTZnMPqVYTkLzZVld3jNvHOQdzmXlCpNKyy96nI1RUDMhC3aaxoqc0H97YQF3QOh2g8zn+fO5+r6MGzYMUaya7XJ5js32C9pr8RrJKEckatz4D3bXAfnQWcwmOqoYRqa2HWHC+QhIANAcNhX2W5g/zvYGGBDR4MXMehubsI5i+g+IABoFzCwmocZIeVIdRMJsc1VYyuFpNVs2jGuZ45EWqTimZARtP2EzyB8fv0ZPU1impshogiwJmiEx2UHOR+atFckMa4ADr4sAAdJtQO9vnr4OlEPPxN489DnWR/dxEIKrUMq
  template:
    metadata:
      name: postgres-credentials
      namespace: dev
    type: Opaque
