{{- if eq .Release.Name "postgres-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: prod
spec:
  encryptedData:
    clog-password: AgBxL9gNPXZsr3XyzJS0svVzFIpNVzD/GCqJjm0Uk2Ya9skG6wb63oeE6GET6UUgoiccYQJJcQzvW1MAd4z72kraXBNk43O3xSM8fw1NzNbovqxLMEK/8ywt/yUDy0pcSlGYnGNPj1S4ehAAd3yomGIcRaH5MV5ENxpVbKYpHISEvkKCLfvMNut642DVy2megQM0nW45pqRkFiyhcs1ecCi45u3lQbA5oe+vgw5aHl6fAMoLlbG9Uwpm6xcDq8mfv9LCTsJ0aa55vPrqai925WGD53Kbvn111WcChU4U1W7ePicxGzDQGd+ccpxZcNFECBglhiHAj1pjV+7SbUL3eiJ3LyLNZQUYvbtmSQT2T+9pO/U/Esa3IEBzWVW90Sb3e1svj4OEhBVzY0hyruHDi9pSMSdciy1Y2JbBbf71F+ZityCUHtvCsMJuN/CKom6HDAwieo3UINENokt0lpNDUjntxlr1oocAKejRANaJCd+wnYvEsToCSOW6cw8GGN4KrTXqoGYxU+wIXC4ar/x/11J3hIoXP2pOcZaI4yU8XkmEQuGzpi5JNZi9wL/gdCWW+H6TGF6pVrJbHRG0DUV66Y0Cc4r9gkxBEVqjtdizIN4TOGutAUHCPA8kUpLCmXcKjNBh98DHymiMdfjr4++sZN17PNPHbGuHH7LZsE7XBJl5opwV6X9pHEumtjKVLSDcDeMNiOdkynKmoO2Dtm5AFmuUEzWvAq/2bnyB
    postgres-password: AgBLSwTTTD/cguQj7VyFVUgDKWgOlIjPcrFp5h+OvpbBibNKGnMIam9NPLrMarxdxu+rIvQ6cgiGQiWqziylQrP34WvfFSKp63Lb9nINh/nObuyYVh42wJIK/nSuJbcbcReCftNkNK7PZ2/32J76TNVkIVF80DTcsCrBzkzUBo+xjgq1/ABrp++Gg3E2nLQ86EwAUgPzmhVVW7OOQo0pgoEki+zwZbJ3DcT2ynsOCS6X2znbPgyE+RZTuSVjcETwimDUY9szdKg0csjWjOg2/0cRGxLPWY/Q9EVBGCbMtxDDgVH1zTPd9PcuUV2RCeKR1jHFG9pGNXL+ArKFkTAglzujIYhi2E4FN9Qkli4vC0S7UV7jCxjAnkPKu/JoyahkwNAo+p7A09hlpM6Z5zKga2xtxd95LffFCVWZnxL+HtHMnQt4kMsJyQLaZw7A7fLsfczReeqMGH9PPjmvoNm9TcOHlt9tU1DL8/5U2Y+aPJZzbNP0cYdruQYM1r20ExAycOUH+RaseSoBnatv2XQ1oE6UGoIgAedEJ7MKX1fbteuW44GoHTVEYrjxuoO62CkIm84C59wzX5zTLvwXW3YsJWupiPcjBkKFo+D08y3YvUQkzFT1mgJCcAeLun2lnrjo/NqdyMCDQCttpES7cJgjsRSBO8LpLpgW1M0QmXIOtyaZ/xjb5rbfkNiFlY7QSVzpj7DpxEOwva5/YoAJx1cYPL1KzaY5jvYFrfcO
  template:
    metadata:
      name: postgres-credentials
      namespace: prod
    type: Opaque
{{- end }}
