---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clog-db-credentials
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgBcUTd+T155LfM+FNIoLIsIaSKhB93aT1Z18ybN2HqjNOzRwhg2BSaadylqfmx1bFqbdx6wX80qY0bPWvsAK61v2MgNS/+F5waJyleL2X2k7/QPA0xNDdvvO3mQda4PZdkrVk2CGFt1LNSgIPqlWALmwO0Z6Qa0fhI8N45/8JzAutL98VUOa73QBDnHbW5Ir+U+O+HpTLpfXVwXo4fsedwNcTlZa8+YSQjVN69JOyVIUq5WawQI2hiQ/haiSMIHFX7iESNROOk46G6bW0jfhwjzqbhB6T7cll4OPLkCkDj9y+I+8SPSStLq34l+KYvFU04CSJMKNFIkuc8Z7jzApfW9eH58CekNMeHMjclghyN7tgnKbcfwL1BohND9xJ9xubWTnQPUl4T/PbtCeeBKU16QAaoHrm17uCIxebgAWyjqAzHyuA9loHTHyu/0WvW3OBhLR7LcdA3iY5kzEGOIOGUFijQ3rGlABF7Cphn2LclRI+w2CsvV3Wf1bH7tj85NQc9Be741bP5Y3kYSmz/u6HJXxqGFr3pIR+sAWD1msAwroWjO9Vk/eIgPx1YoTqHZDJ+u6+BlGYxNrgUTc9B70v/cdAN4RcBf481sLuFLzgCBbL5MiDIFpYIm8CfewoQgfcki7Dl/QAF7CPegz/ZWcGRsQcAwuX1k8PfwJakhIgM2Z6GwM9hYQD+jaDEpy00dhjBeV7dZYs4Jr35MqfJuN8aK7WQTFt4pfxVB
  template:
    metadata:
      name: clog-db-credentials
      namespace: dev
    type: Opaque
