{{- if eq .Release.Name "clog-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clog-kakao-credentials
  namespace: prod
spec:
  encryptedData:
    KAKAO_CLIENT_ID: AgCY0hhf3U73x2ZZeU4+dPpEuF+1TyYSgEx5JfA7GVh/ORHmeJ5FMxCqftNYNPBSnKMwoVTbO8p/fqV/WzdGas7E3o3bU36UtTc26PmF0x+pGpcmGucZukUaUBZRdRrjrrJSDITWx2Ed3Meqxg+rMsOvKY+QFNtEX+GSfWS4F7MK6D2P7eGM1b4xGU0dFqTNz/WJpm3kdX7ml+1KIc2YEkOcB6xDHKAt3VT2NQH0H+f2J6tbfZ3SXIS0WgDqLjMSWC9FqbRYcxzDer8cP9Xgpko1MqqGtdZwqukXTrZYwhSLQ5UxZLi+VmOwnqw0bHgYZgePSKtySJsZnOSnszEe5SIgYzIITtPRQFpw4Ba3CMeiWvBX9cyJRBGpMDTicNFX6RXPTqKYyuFmkqtmn0zCR2qgrHwJKDPFoPtJhewGJ/QnZFc56c6tyARDeXxBPVUn8cB9I10YDBGnZb2Rt8p83Z49QFIhlt2rWJvOIm8f+XGbeMaGmrkVYVVl/NYYMH9f8550wDG/GxGmInoLQaMHpzKBPqofvV3E1KG360sHUe88lisJOL1In2jj6Dw0pam2b/lZDK01z8JmIu9evdyR6uHoVQjF8fAN191UGmOGiL50KHkzaLmW1LspbfUbJ0zSCwWj3N+EB03R4UVY155q2KHEoYis9AA0Pm2c36ibJ1LfPOjRzzbOk/SxhthBrJ86VjTzwhzMOngPvYK9HuMWvfBVeYLQQSqlN1h0HDX8yhYy0A==
    KAKAO_CLIENT_SECRET: AgCNFhvoep2/0UmH1hrTBsD99ib3+gnHlWqNF4lx27E5PI0Pkjn7+Iu59xfnr/IIjpEIhike85Av7ca6bMoYY1xzaIzr+QXnUvDdL04oWMT3muxHiZxLdg7ZH9/XTaAY1v/BYWbU+USqSYE22R9PdHqXCx48SFqdte06Af4cgR7cwAYCJRz+7U6IjjTHzTzMX24QLgk23I9aTO2ArLpT3+2zODvvd7TZz/Ihw6mQ4g7ieKMQqmtIxdH5fI2MHTJNfYoMuZIf+OT+3ajHtecddLIKSkVkCezKn5orMwoqgR262fnm9/tta1dlczwbSfzRzmnsD2i8DhZ1DOKqUbIroLFpjZGxYpk35sTgW+Vi3Y6OO/moQiKCdbg4xHbhr/qh0FTnFYs+IAUZw9b4DsTvQHLF29CVngWLYyI4lCunz/mjzeE7DgzZ2y2aFfwQMhk6dRWZDTPJuGbXQGak1+S8nay2bDUmp+LCnRC7mc9dSAR5KWQydma6bWj2WrgunVWFR2vhZJnqgSF4N7hm8YFrXCbENLoVLIeYeshhCQC5Lo5jzO/CVvNomU4hdZdpFmYaSnZchVfmZE/m62Byr+Jx1KrToQK+npU2IW5HXjzF+2DVv+riLhT3DtBuutzMlr2qZGyrM9Kn2dxD8+kteK1bNuegaK6VZbIKDobDbw2CWuq5CIkMBH/j1Ifkg+AmV/r+De+ucKENqlosf25XEB6X2+nKUgPUPhdh5wCDTPfFmBckOQ==
  template:
    metadata:
      name: clog-kakao-credentials
      namespace: prod
{{- end }}
