{{- if eq .Release.Name "clog-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clog-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCbyzmFc6gmsQdWp0LYcvH+6Bn3qUiy5l68ohxj7nqaqnu5qAKZZQoT8n0GTNa3nIP/Om9oXl+bn1NQ//C5HqL+SHQVw2h/41BZWFMe9v7NniszFmWBzg3pHSohCJrKnFh21fQcMKBWitOusz6KDKeH+Oj/wXfgED6aS4TaE2xMRultdHp9xx5W538UdCghS+wD75Kt7AFzoeFqpAHqJnHAerNiT4zsFNhlrZ2MpNBdSPpM3JIwjao/T1RHc9HA64b/J+xSKauiMRLLuXYmPPLQx24rPuRgl095SDhcUBsBvUr+j28jZXU6y84b+0b+Mv1F1wI0/pdh3SnlWLTqw+MfEgnfhSYfK+SEKUJ6RojnS6eDLYjn3V4HHsYu5NenO6xo/Tzn+ssd4oUC1sKSxTlbO/0md1Jgsd2jtCFXNofYpz80pzfwjFoJFPiZLiWVC2BLtWlan9HWsHtj9ysBB+yk6CqT4TcioUyW4m4nUiluwrYSZDEJ9T9apjH7RLeHIoWIbt8WuI9qXY/RvdMqVXNJgghjPQFFOyvJwriaP59X1Da0PJziQrgG3ilWZc6YXfBf8AKVbTKxZLj7cFDW8XRVtLM3D80rUZ8OgUjcBhSpHIVMOWI/DPnW2yQH1VS1U3f2E3yw/fPE0fSypCvIDmdNkRctLtVu7S2GXZrBJgdgzKoWAHadDtJK7Xae8RykthYrWVUHqi+p2LAKnFL8EayerRuzLibViedD
  template:
    metadata:
      name: clog-db-credentials
      namespace: prod
{{- end }}
