---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clog-kakao-credentials
  namespace: dev
spec:
  encryptedData:
    KAKAO_CLIENT_ID: AgAG/8ASLoiRf8ZZRU2oCHwedD7KLTh1DW6tkeCswgRplmogGCHZ9U9AO9IInP8YRKyd7lltr0AYw+dO5x1r+MK7YnNXyMpmDNijcSMdXxyyThDzxboik3pDiZbX8vBOAOIREb23GBoQ+LmpEQ4flSo5blhjiq/7mXZUK7YQS2BuQtTPd3dqos8wtd3uIJwKJqz3izpCWZIAWpIlLRg+trRn75e0COBxY/7y5v/Sz16AUE5k3rJx/CxAUJWaQK2Kb4pzUavzJdzfbdU0pB44bwWclBgN/ntFeCziA6UE9BSOoMAyOEEmI2bwFo4NcCRQvSgyvV1flFU0hI8UFg/cmkeH+SbGHP6nvgyE8CTEUDzO6Kl55f/8HbWUFwMlDBIYS5cU0Idbgwh4kRkhdFKg8Y31v+F1tdlQhfVCmDO2iBl0GVM/uA6ceUeNVqkThMMfr4IqQmF/2PZx4+tX4vrspJBXHshG65qXZMPqR+v+6bl66Ua7cK1iAdF2e8PVE+2Fjd9O0h+GqnIoZVsTUUPfijUQ7QdThD2I7aUt2DVFf7VZ8NCGqE0V3ry4G5NEfsCYMmfIADPNI/6ppaKuAYb2RhlQfIjJdSie+1WQgw/3XsifDFW3u7IbGyU9xayApRjihXPUBmEHrww+FbytNS+cXqNn7Pg0798Czn40mtwRGu5Aeo8mUe7+82KUWDbFck4wMB8A8EkkUSYHHoN9R08OUwTVU2aazFXT2W4uCnTvJ6nM6Q==
    KAKAO_CLIENT_SECRET: AgAeEV8FMe22hlMheTVVFFYadEZsuKB8TnQD3kI2hnSrGJQKDlmRaqKcza4tpkEimN2x/9gtDJZw6eM0UNagV0ExReNQ5FutPXfx26vy3q6A/pdo/bOUZZSJ1eyXsY7hD+apCN00rmV7F+avppx+IqAGdfMEYf20JkB6bFGgpd+JLDwUb22wYTwIF/ygg3vmVDh72ID7PUMc/pJWtmIU4XFKmQw3fQ+YH1YclIh7VIw9r1WSqT+bsbo4dCuSvsZICgY3BO869zQAt6SFZimjgaJA0GxST7USdjwweMbgk/aqUkeQ5554FyDAOwE0FXfPM9W4Tth+lBaKCr+KsFbhBFsEhXmTx2yDdikV4sYXpQUx/8reFd9l2EI1TsEdm0Lz9mxpZb7JtKuPsjQaYd2WoKhwZxnKVBOI3pk5qs9xOsjIkMOUmI0AyJYTba7I4K/qg9dHDmbhBdzdmSklMMZ1Bt+BMECUr5AFfgr2AWoXGlZlmU2SWqix/Mp76ahjUpH7Bv23jZsJV8y8Lo4I3tRSt1ADMV9lg25M4xq5hKAf5V0Sp7yVPomGsJCy1NjJ+Vinkej3aldrwlq7fIm+yGz4JNFlHQVfcxZUVQwzyhHEuZXc1tUt6bcb5C4fQRS5uEA/ss70xpm50uf+hBd6TDEfCXl+vkkMA+9rzo2OIPkwzI21KHOaF8XKwSBuJYr46KDjUz1xAOlSgI3aX9oWH+cZasJvNs8kDUnXWNzq/85nm/q1Kw==
  template:
    metadata:
      name: clog-kakao-credentials
      namespace: dev
    type: Opaque
