{{- if eq .Release.Name "clog-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: prod
spec:
  encryptedData:
    TUNNEL_TOKEN: AgDORyBJpP9egnD1CQcpDDEMq9vNws9+amb6ExBqBF4YZblQwvTXnNjJSksRbefBHu7gIqovNW3HSy9u6a2IbNpNVgGmGlydIXjZlRfq6s08sxMVMxExNOaOEJP0qf6thAeTE7vkP8L2MfEVZ9JkBBUTbru/0Nz9RGeD3P5SOVUHbsE03UelFANQRfLOkRjtD2bgkkypsA83Bukh4plOA+/5gGecuIEkMCkOe3MHPEr2DImPoumtccT3p2nk9sixE4BhNZX0+62ELYpEAOwWg4VLwx29Gr4YwffBnszp9FK/76um5v8ky3+r/yoc5xVO9PPR3R6sjhd33uY6AK9ZDl3ViIjGJ9LZpuQo/0TmoXezqmLSesmNmH0vcIj2TEQKp7+AK/FVI9QtSwHWDsSP/RM9DV4YhNscXzrDoMRE+7lHG3jhAfmf1t2sAU/yXTvj11wcr83gWx7buTSFPN4IPwkcQdk3ouoPzsrPndLNi8VIVQWFhP+h3HVmxO40M8mZb1Q3tULTtDV398Ewok9qrApAF62oUsMDUZOMrrp+eyMBYeTS8kFGv3hcThDiWkmdCWsjPEBxpUgG5vPf1iVgBSwCerpsxgVrHwlEFBJiD73gpBaaofrkgHf3R1Jr29+n0gij02r7gDcNAOLHCEhcGtrFhyDCGCuLr9inDTK/ksXtcm4x3r5hdhAey2DqMsBTINE9DE2Mtk79qzhbvTzjK7wa74mXXTDmKhS5nrxWgLUHGX6yvX2oUF7NL4f2Ln8mWKSlzbxnQdhV9wF9/ZJWCyc9ZZFBSk79nqiNEJp8lEDq1AAEZyqDFL4rMC5C4wBrvZozB+UVWZ/CDXqAHOPERFB1OGKaq32FcCVpulSb9cFGMq1C3wQWmAHbdf/AKtSLBLQIkYf1BLq8sdwyXeyaodwTiw2C9juydeMkyFZrimuYTfw2F9wwrzLD
  template:
    metadata:
      name: cloudflared-credentials
      namespace: prod
    type: Opaque
{{- end }}
