{{- if eq .Release.Name "clog-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clog-smtp-credentials
  namespace: prod
spec:
  encryptedData:
    SMTP_PASSWORD: AgDTI51WaZcv958Vt7Q9CYfYQP7ePIQY1X7+bL/4cOeSmswtn/TKPpbxabQ6N7C0J8oAKga/3Q1zjQoAEtS50lJlWYByYEegQzNg7cLp7Xz11ogDEW0tsyg/jNFUO4e+C2DnHiUcrX0jXMIcPfdM0+wze5QVO26BCo2XHIcVJuVTATD2timkRLgvKLe2q5x93ZyTrx18AM1v+RHlMH5fsNXVa67SaHejdXEs4Rg4w4MMhHkSzlo/LVs/yvLbbsJoBK7e/ycuNbLbQOu7NhbEUfR0WGJKjw5RyqO6dKFtrr/FBQNgn+GPADwYNAFJD9Y51aXiwY6YAsIUWIf0vkKwEikbA5g/YGfVfIobrnMB342Nfw1j6IYLOxQC/662XZE+hDNfhBn2wPhVd39fZTXxSGL+kNf2l4agLsCicAcVHBNZtWwM7pACssnkxAoZNwHoebJDY2ti4FDbgmA9ZgELirt8o27quVQjlWsko4DPZNpIrpGQX6f179XRJ/7SvvV6xFtawLG2Ol1PpXghM+iafzYPhO80kW/E1I24UgEXkQf5joxC7GPWFdI7U87iCbwLdKSP1B++PLd/jDaIpBEtS3Ft2IyzSNXe1OTd8eoLYwCCXyjzTOMsDgpi+UZ1R3GioIuKpp8bdVQqU9+SKmgt+mlrWIR9MHiD/wBXK9mL8R3bY/XxfoIOnUs938zq0qQPDnbHZSYMWdaNfs5SLFOq4rCa
    SMTP_USER: AgCsKhFZLUdBI++zyTn0lekxI6DosqelEqdbTc4sqfEcf3kA/nZo2vFFDBjV7enTpr6mjTFv+L3qLM4oeBQl9ApPQ62ALa/EsFT3RMm6rRdmQxOy3GtHxY71BnZGh9GNxiF9s1Xzffz5XuFBYhsOq1Cqm7RB0jCCVoyzMc+S8SiYN0RyF5P5gVrVhkW12wddSlS4ZsXB0kjDUNT58OBNHj0tbgYJT4A7feat5KrlaBodyAZqnhSalmPW6ajWlJQMj2HnlL7qTBfE10LO3ZJV7OqyXOpqJGRF+txe1pxznm5r3g/scR11ojQhEWeHP/dfgIDr6/npncAaGhffufL9bUjdbTOQav9KhCwvt7cDFOamSrQ7ENVMum7YXo766AQ2SzLe7hApN4rs1BatWKBU+ekSjpryGgphxQFHc72URK6ZR+kAhkcpVYAZU1dLhCMLFf3We9cntHNA6vX1HBdDkUnkL7Ai6e7EntrpNKv65yWjZDE/1fMQzrkEB0kh6YlSY/HL2NpEjtV7ISOd0pxMT90qbM/wbGYqmXWRVH1KI6chhoD78NhlCov6r5jkgbsIkr0hFJSH6WQ6PdPLX/HPjDAvBvh1UtJoT4Ml0Dpxcr6W0T781+grfeDWeHBMLF2V/8pCwwBtx0u2IIUVJUl5CYveXR0Gq3wFDV0MTAV6YNuCWHIanwOS/G2wFjjzBytVarRI8AEEXhgOLmH0yL//0F/ZHgAf
  template:
    metadata:
      name: clog-smtp-credentials
      namespace: prod
{{- end }}
