---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clog-smtp-credentials
  namespace: dev
spec:
  encryptedData:
    SMTP_PASSWORD: AgCGKA/1zsV/Z4ZRg0ETjkqfHO/T3HRq29te+sU0UIJ3gVtCeYkb6M4aKkvfHVzOxIwwKtkvcOQ7f7Oq3l5TLrgt+cW1gykKlK+sJbtHEKCW5gQyn2VwMs6BlpUrnHrcGgjuIQQ42mT/+5gfZXGAJzWk6xcWXsMb0bikc1yPqJRyLbT3S4xw97hKC+v59M5HKScMYbH3/F/0JRoA3vG5xQQRoDZPZl212g7x9LgZruXaJherUUWflaFNo0TVXcWS1X09vP+0mK9YUaRORur0kUY8QLITh59Nz6XiKkeaQc0Bu54miALewgmF9do2XyrblRRGHuwIpKK3bTYM/NW7K/ABX0tPqq9AuauPimLl0ygKgdN91vKP2+cSWJ4nKVfOXaezwlsbLS+3c+AE+E/8pW10lRGLakPMk4Q+wOwBDR+jz1Vc94wF0aql/FVxG7aALJaH347elKJXbTvc0V5jeFeH68aTZp/kHc8Oe7vhefSbduWtCfhegS+LevUwh4UqJ9ghq5UtAbv0TG3aJiY1tw92al+AsX5Yy68JxIMwhzKyzKiuD/s8xdd1VTY2n1VScJ8gpKOzHt3SlAM5wHH6gxJCDFHIf5CAUXTso72FKh95+7s0BtJatOe5myeKWz2meFvyZ1V6FAKRE9OoBai4i9Clf9sg4GW5xz8HFl8l1sTA1nGONuz+IlmoVOeLDqUq5hsbAJ+aJ8cDBwtG/WvJxXVc
    SMTP_USER: AgAQXwTCWRMwHaDuEwXP4BMuik9v+6IhGm4ArUs6bgjhXnY9Tse3eDIx4me6OpZRiQ0ZwK7bTln7yU5+nTuP/euHUUosO05gn7q5KO8X+iDxIGTNqTvjD6vFaEj4VQxtcK/0Tv5K6TYb8qQwaEmYmaWjraupZiS8cNVdTzo8elWmbK/LhOKWqxEFhMZiycONxV9UkX2Rk9NixkcqL3k9oHHw1OAf/qTpe9fRNKChJqf1dYqxnSZqmQ/2NhSQjWwbn8Avz2evsUKkdYqWG/0YXGg+APvMJU1tHM+AozJjaQYM9V38uX5UfQl9hvddBl4rNrOA8mOdEYX5oc7PO2RydKflRuzTHDXfqpak0UrkPK8TrlkDv3fxXEbz7R/Y9VD7wGmwZK69hjWBpUDM2XNUJh7kIt5/JJodHnvNomq65e0gL6GiKIEIWoXxPlhL8b54CFdi77j3Eckp3A7/sX2zJ77LOJ1g5+R4Rjlgai3ESxOi7fj9V07jyHpLKTrzEgb9MVlb5xxBkoIUnPbat6HMZQpyaBidYaRxB9uA9gAddzRMQNKsD/HWgTZIwRSRfnXSfk404aqe84zxMOYALjeRPuO7TQV3JaDmTc9pprJuTv6PidGVFEPkVLQIQ8wG4bO5O0DzVtzLIloMsValXFGApOzLZXozGLbTDwMoI/Ry60bdNy5xVBJp5L+W8cM8aQsyDeCD8ZlXrWG3LCI7qrdiGVIYyLxh
  template:
    metadata:
      name: clog-smtp-credentials
      namespace: dev
    type: Opaque
