{{- if eq .Release.Name "clog-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clog-redis-credentials
  namespace: prod
spec:
  encryptedData:
    REDIS_PASSWORD: AgAhlxQ5rNAeiY24sZUMDh8lpqHEdSl5ciez4nGYCSM89f/2onBjVTCw4wml6FWBi9EYREel/Xh2Q/5vfOCRz0eXnfp+9AXL02Juml6zz3UhU4xmy9BZB2VU2g/bpMcstWIQpR1YmVAGd/k9ULn/+R3vTQKTRZcVN6F/IgQoYW94MuXpKkB30ejzv40JPM05EU3J+Od+4HQUIpHnOXPfs9oJ6QMwLITVMEygOGFA1DNC+4BuKqhTxKpLbUDfkVVLXlneO5uKPatg3eV5X78EfrVLAnpJ9riDxW+b/EKvd3QPuw8G9aW3vtdmqttfTBdFr9rKLwE8GWRZgdI4IfnPDgMba26u7swMra0X+OVmUnE/PMdaiE+lpSe5Map6Oh67GTPQ6P54zHZue65jwHjlV7xKOAYndjVeq/lGy4fP2AZuPqnmGPBI8ejqv/Ah2yMXZrLgGJaNh1GjwoJPZeydSBKfhsNm4GOYdasbFO9SGttn5DyPmLFSPWJG6jmm0NELM8wOiCIlIArHWHzzpATIyvAet4l1uMKazEFcviNcrBAQcuojbYEDAy9t22nJa7GFETcfkpR9340kRUL47YrqtAIqksmYWF/8gQ5/4fMwsqfcAQMvYsHD6VdN8T+woKDmHSgSrS5aOdeOUaCYnciJNeg8wIHrcCNBo0Z4ZsgAF9OHhK5gtPmBB/cyTVM71wh1VldQ5y+g4mV7sJ3F5TG9VhSoRPYYQw==
  template:
    metadata:
      name: clog-redis-credentials
      namespace: prod
{{- end }}
