{{- if eq .Release.Name "clog-dev" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clog-redis-credentials
  namespace: dev
spec:
  encryptedData:
    REDIS_PASSWORD: AgAOnUFHlQDDfOzveSX5tXeickYr9LhbhkgUZqMaFUZN0IST8mop+lU3mOBj/Mj+rTpw0OfeWmgQMAua+zS1bx/kJ9QhLx/nyd9JHjv6Pb99Ieyk4Y9P2+zWOcL/YBwkwo6oYp/dF4xDewyWChNJAXneO6E00XWyiUfX2ZzSliFb6RCgJDJa2LyE+k2Wx5gYfewlHR6fZbm+85/eGXKHTo9WV0suKbWv2G3ZwYzEGOuXa9gNO2zXb2oP9mmWfkMJo5JWwI2vuumbdIxzr38pHFM12rNtbmhFRLbjD7HSppGAvQg4Jv9W0fECKSc0zwjH+R29XcgGlhVqELqFqT1KzFdEKxO0lgZR5ZCIPi+bbrRBzC7EveE9j12WwutQiFbHntajvOw4O5yqxGYESDruYiy3ZIjZRiMrGS4DkZtEDtOVqllhuxgO3V/jvuZocV47xJqPoFdN/ST397S4BkMV7VSUoEVTV9WHFtnQOVxOxFtANave3igBddD0vVUdEThhaZ5tPS/0+9ijEvkUY7tQ6/IXndlhHToJut8FW8UVprn0HFa37oF0T4ad5eL6GFQyYxMuL3DU6Wc/75+uoGO1zBaH/OXYH11Fl7MifMFUutAGtS+NYEKpEob9bcG116pRYMrlKOqWz+BY2ElVNsyxIFsEyBWP13oY6SU3/72iqQgqfXv9mzg0sfa783moFRpAyqedYxiXkffGVpViPeIs2m3tRtuOJFcdTjdB
  template:
    metadata:
      name: clog-redis-credentials
      namespace: dev
    type: Opaque
{{- end }}
