apiVersion: v2
name: clog
description: Clog - 클라이밍 기록 + 커뮤니티 서비스 백엔드
type: application

# 차트 버전 (Helm Chart 자체의 버전)
version: 0.1.0

# 애플리케이션 버전 (이미지 태그와 정렬)
appVersion: "0.1.0"

keywords:
  - climbing
  - fastapi
  - clog

maintainers:
  - name: miginho
    email: jinhoya89@gmail.com

home: https://github.com/miginho12/clog-backend
sources:
  - https://github.com/miginho12/clog-backend
