apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/miginho12/gitops
    targetRevision: main
    path: apps/postgres
    helm:
      releaseName: postgres
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  # PVC 는 처음 생성 후 변경 X (StatefulSet 의 volumeClaimTemplates)
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
